import numpy as np
np.random.seed(42)
print("=="*50)
print("TASK 1")
print("=="*50)
scores=np.random.randint(50,101,size=(5,4))
print(f"Scores of the 5 students in 4 subjects: {scores}")
print("--"*50)
print(f"The score of the 3rd student in the 2nd subject: {scores[2,1]}")
print("--"*50)
print(f"All scores of the last 2 students (all subjects): {scores[-2:]}")
print("--"*50)
print(f"All scores for the first 3 students in subjects 2 and 3 only: {scores[0:3,1:3]}")
print("--"*50)
print("=="*50)
print("TASK 2")
print("=="*50)
col_mean=np.round(scores.mean(axis=0),2)
print("column-wise mean (average score per subject):",col_mean)
print("--"*50)
curve=np.array([5,3,7,2])
curved_scores=curve+scores
print("curved_scores: ",curved_scores)
print("--"*50)
row_wise_max=curved_scores.max(axis=1)
print("best subject score per student: ",row_wise_max)
print("--"*50)
print("=="*50)
print("TASK 3")
print("=="*50)
row_max=curved_scores.max(axis=1,keepdims=True)
row_min=curved_scores.min(axis=1,keepdims=True)
normalized=((curved_scores-row_max)/(row_max-row_min))
print("Normalized")
print(normalized)
print("--"*50)
max_index=np.argmax(normalized)
row,col=np.unravel_index(max_index,normalized.shape)
print("student index:",row)
print("subject index: ",col)
print("--"*50)
above_90=curved_scores[curved_scores>90]
print("Scores strictly above 90:",above_90)